// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/google': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/google.post').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/competitor': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/competitor.post').default>>>>
    }
    '/api/create-checkout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/create-checkout.post').default>>>>
    }
    '/api/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/generate.post').default>>>>
    }
    '/api/keywords': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/keywords.post').default>>>>
    }
    '/api/market-research': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/market-research.post').default>>>>
    }
    '/api/ping': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/ping.get').default>>>>
    }
    '/api/stripe-webhook': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stripe-webhook.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}